### ISSUE TITLE
Lakeshore controller: temperature attribute

### ISSUE THREAD

**Issue by prjemian** [APS-4ID-POLAR/ipython-polar#13]
How to scan the temperature as `temperature`?  Can we redefine/alias/something `self.signal`?

**Comment by gfabbris** [comment]
I've done some thinking and testing on this. The one thing that I don't like much on the ProcessController is that (as far as I can tell) the class doesn't behave exactly as a Ophyd positioner. That makes things a bit less intuitive. For instance, one cannot use RE(bps.mv(temperature, value)). 

I looked over what NSLSII/CSX did for their lakeshore, and they set it up as a PVPositioner ([Github file](https://github.com/NSLS-II-CSX/xf23id1_profiles/blob/master/profile_collection/startup/csx1/devices/lakeshore.py)). So I decided to try the same (it's in the #13-alternate-lakeshore branch). The issue here is that PVPositioner looks at a "done" PV that is supposed to do the job of checking if the temperature settled. They have the same 336 model as we do, but I don't see a done PV for ours. So I tried to go around this by creating a Signal that is supposed to work as a "done" PV. I've done some preliminary tests and this seems to work ok, both .put() and .set() functions work correctly. The one issue happens if I do RE(bps.mv(temperature,value)), and then try to abort it. It raises the issue below and breaks the RunEngine (ipython needs to be restarted). Any ideas?

In [3]: RE(bps.mv(tvap,300))                                                                                                                                
^CA 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
^Ctrying a second time
^C^C^C^C^C^C^C^C^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/bluesky/utils.py in handleWakeup(inp)
   1431                         os.close(wfd)
   1432 
-> 1433                     def handleWakeup(inp):
   1434                         # here Python signal handler will be invoked
   1435                         # this book-keeping is to drain the pipe

/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/bluesky/utils.py in handler(signum, frame)
    178                 orig_func = self.original_handler
    179                 self.release()
--> 180                 orig_func(signum, frame)
    181 
    182             self.handle_signals()

KeyboardInterrupt: 
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _resume_task(self, init_func)
    889                 try:
--> 890                     self._during_task.block(self._blocking_event)
    891                 except KeyboardInterrupt:

/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/bluesky/utils.py in block(self, blocking_event)
   1489                     if vals[1] is not None:
-> 1490                         raise vals[1]
   1491                 finally:

/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/bluesky/utils.py in handleWakeup(inp)
   1432 
-> 1433                     def handleWakeup(inp):
   1434                         # here Python signal handler will be invoked

/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/bluesky/utils.py in handler(signum, frame)
    179                 self.release()
--> 180                 orig_func(signum, frame)
    181 

KeyboardInterrupt: 

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-3-228fe1522b51> in <module>
----> 1 RE(bps.mv(tvap,300))

/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    805             self._task_fut.add_done_callback(set_blocking_event)
    806 
--> 807         self._resume_task(init_func=_build_task)
    808 
    809         if self._interrupted:

/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _resume_task(self, init_func)
    908                     # (per decree of Guido) thus we give it a second
    909                     # to sort it's self out
--> 910                     task_finished = self._blocking_event.wait(1)
    911                     # before giving up and putting the RE in a
    912                     # non-recoverable panicked state.

/APSshare/anaconda3/Bluesky/lib/python3.7/threading.py in wait(self, timeout)
    550             signaled = self._flag
    551             if not signaled:
--> 552                 signaled = self._cond.wait(timeout)
    553             return signaled
    554 

/APSshare/anaconda3/Bluesky/lib/python3.7/threading.py in wait(self, timeout)
    298             else:
    299                 if timeout > 0:
--> 300                     gotit = waiter.acquire(True, timeout)
    301                 else:
    302                     gotit = waiter.acquire(False)

KeyboardInterrupt:

**Comment by gfabbris** [comment]
I need to do some more testing, but it looks like it's working now!

The two things that had to be tweaked:
- The "done" signal had to be subscribed to "_move_changed".
- It's good to have a meaningful "pause" function.

**Comment by gfabbris** [comment]
Tested during experiment. It works!
