### ISSUE TITLE
__pycache__

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/ipython-polar#15]
@prjemian: Should we add __ pycache __ to gitignore? As I understand this are just temporary files...

**Comment by prjemian** [comment]
Yes.  Any of these files are a good list of things to ignore:

* https://github.com/BCDA-APS/apstools/blob/master/.gitignore
* https://github.com/APS-USAXS/ipython-usaxs/blob/master/.gitignore
* https://github.com/aps-8id-dys/ipython-8idiuser/blob/master/.gitignore

You could copy (or copy from) any of them.  All are slightly different.

**Comment by prjemian** [comment]
In Python 2 and before, python wrote its byte-compiled version of a `.py` module into a `.pyc` file in the same directory as the module.  This is an optimization when loading modules since they are not modified as often as they are loaded.  With Python 3, that pattern was replaced by writing them into the `__pycache__` subdirectory.
