### ISSUE TITLE
Colliding _Time_ key for multiple scaler channels

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/ipython-polar#21]
@prjemian 

I've added all devices to the baseline in the _baseline_devices_ branch (for now, in the future I'd like to be more specific as to what goes there), but as I tested it, I got an error that said _The colliding keys are {'Time'}_. After some investigation I realized that the issue is that both scalerb and scalerd have a _Time_ channel, and Bluesky doesn't like that. If I change the name of one of them it works fine.

Is this an expected behavior? I think it's not a problem to have a different name for _Time_ in one of the scalers, so I think it's not a major issue.

**Comment by prjemian** [comment]
Yes, that's expected but I don't know why it's required.  If the name in
the EPICS screen is Time (or even worse "time"), that could cause problems
since other software uses the same name.  The standard python time package,
for instance.

Basic guidance

Do not use an object name more than once.

Do not refer to an EPICS pv more than once.

**Comment by gfabbris** [comment]
I think it's required because the name of the scaler channel is used in the _baseline_ `pandas.DataFrame` (rather than something like _scalerd_time_, as it is for `Devices`), so it will end up having two columns with the same name.
